"""
RAG CHATBOT MAIN ENTRYPOINT (chat.py)

What this script does in simple terms:
1. Loads the FAISS vector database and metadata map generated by ingest.py.
2. Runs an interactive conversation loop in the command line (Terminal).
3. For each user question:
   a. Uses a Router (router.py) to figure out if the question needs static database search (FAISS),
      live API data (e.g., weather, deals, stock), or both.
   b. Retrieves the relevant text context snippets from FAISS vector search and live FastAPI endpoints.
   c. Sends both the retrieved context snippets and the user's question to the Groq LLM (Llama 3.1).
   d. Displays the AI's clear, grounded answer to the user.
"""

import os     # Operating system utilities for reading environment variables
import sys    # System utilities for cleanly exiting on missing config
import json   # JSON helper for formatting API context responses
import numpy as np  # Array math library used for formatting query vectors
import faiss        # Vector similarity search engine
from groq import Groq                   # Official client for Groq LLM API
from dotenv import load_dotenv          # Loads environment variables from .env file
from sentence_transformers import SentenceTransformer  # AI model to convert user question to vector numbers
from router import keyword_router, fetch_api_data      # Custom routing and API fetching helpers

# Load secrets (like GROQ_API_KEY) from .env file into environment variables
load_dotenv()

# Paths to FAISS database files on disk
INDEX_PATH    = "faiss_store/index.faiss"
METADATA_PATH = "faiss_store/metadata.json"

# ── Safety Check 1: Ensure GROQ_API_KEY is configured in .env ──────────────
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    print("[ERROR] GROQ_API_KEY is not set. Add it to your .env file and restart.")
    sys.exit(1)

# ── Safety Check 2: Ensure FAISS index exists (built by ingest.py) ──────────
if not os.path.isfile(INDEX_PATH) or not os.path.isfile(METADATA_PATH):
    print("[ERROR] FAISS index not found. Please run 'python ingest.py' first to build the index.")
    sys.exit(1)

# Load the saved FAISS vector database and metadata map from disk
print("Loading FAISS index...")
index = faiss.read_index(INDEX_PATH)
with open(METADATA_PATH, encoding="utf-8") as f:
    metadata = json.load(f)

# Load local embedding model (must match the model used in ingest.py!)
print("Loading embedding model...")
model  = SentenceTransformer("all-MiniLM-L6-v2")

# Initialize the Groq LLM client with our API key
client = Groq(api_key=GROQ_API_KEY)
print("[OK] Chatbot ready.\n")


def search_faiss(question: str, top_k: int = 3) -> list[str]:
    """
    Searches the FAISS vector database for the top-k most relevant text chunks.
    
    How it works:
    1. Converts the user's plain English question into numbers (384 vector dimensions).
    2. Uses FAISS to calculate distance to all stored document vectors.
    3. Finds the top-k closest matching vectors.
    4. Looks up the original text for those matching positions in metadata.json.
    """
    # Step 1: Convert question into numbers (embedding vector)
    query_vector = np.array(model.encode([question]), dtype=np.float32)
    
    # Step 2: Perform vector similarity search in FAISS (returns distances and matching index positions)
    _, indices   = index.search(query_vector, top_k)
    
    results = []
    # Step 3: Retrieve actual text content for each matching index position
    for i in indices[0]:
        # Guard check: Ensure index is valid (-1 means no match found) and within bounds
        if i != -1 and i < len(metadata):
            results.append(f"[{metadata[i]['source']}] {metadata[i]['content']}")
    return results


def generate_answer(question: str, context_chunks: list[str]) -> str:
    """
    Sends the retrieved context snippets and user question to Groq LLM to generate an answer.
    
    This is the core of RAG (Retrieval-Augmented Generation):
    Instead of guessing, the LLM is forced to answer ONLY based on the facts in context_text!
    """
    # Join all context snippets into one clean text block
    context_text = "\n".join(context_chunks) if context_chunks else "No context found."
    
    try:
        # Request answer from Llama-3.1 model on Groq hardware
        response = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {
                    "role": "system",
                    # System instruction tells the AI strictly to rely only on provided facts
                    "content": f"Answer using ONLY this context. Be concise.\n\nCONTEXT:\n{context_text}"
                },
                {"role": "user", "content": question}
            ],
            temperature=0.3,  # Low temperature makes responses focused and deterministic
            max_tokens=300    # Limit answer length to keep responses brief
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        # Gracefully handle API errors (e.g. rate limits or network dropouts)
        return f"[ERROR] Could not get a response from the AI: {e}"


def main():
    """Main interactive chat loop."""
    print("[RAG Chatbot] Ready. Type 'quit' to exit.\n")
    while True:
        try:
            # Prompt user for input
            question = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            # Gracefully handle exit signals like Ctrl+C
            print("\nGoodbye!")
            break

        # Ignore empty inputs
        if not question:
            continue
        # Exit loop if user types 'quit' or 'exit'
        if question.lower() in ("quit", "exit"):
            break

        # STEP 1: ROUTING - Decide where to look for facts (FAISS DB, Live API, or Both)
        routing = keyword_router(question)
        source  = routing["source"]
        print(f"[Router] Target: {source.upper()}")

        context = []

        # STEP 2a: RETRIEVAL - Search static FAISS vector store if needed
        if source in ("faiss", "both"):
            faiss_res = search_faiss(question)
            context.extend(faiss_res)

        # STEP 2b: RETRIEVAL - Fetch live microservice API data if needed
        if source in ("api", "both"):
            api_res = fetch_api_data(routing["api_endpoints"])
            for res in api_res:
                if "data" in res:
                    context.append(f"[Live API] {json.dumps(res['data'])}")
                elif "error" in res:
                    # Print warning if live API call failed
                    print(f"[WARNING] API call to {res['url']} failed: {res['error']}")

        # STEP 3: GENERATION - Pass retrieved context + question to Groq LLM
        answer = generate_answer(question, context)
        print(f"Bot: {answer}\n")


# Entrypoint guard: Run main() only when script is executed directly
if __name__ == "__main__":
    main()

